name: PastelPlugin
version: '${version}'
main: io.github.yoonseo.pastelplugin.PastelPlugin
api-version: '1.20'
authors: [Juho]

commands:
  pastelplugin:
    aliases:
      - pp
    description: "pastelplugin commands"
  quest:
    description: "quest"
